services:
  app:
    build: .
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=image_gallery
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_gallery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
